name: Deploy full stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Récupérer le code source
      - uses: actions/checkout@v4

      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo mkdir -p /var/www/todolist-backend
            if [ ! -d /var/www/todolist-backend/.git ]; then
              cd /var/www
              sudo rm -rf todolist-backend
              sudo git clone https://github.com/wololobzh/todolist-backend.git
              cd todolist-backend
            else
              cd /var/www/todolist-backend
              sudo git pull origin main
            fi
            sudo docker compose -f docker-compose.yml pull || true
            sudo docker compose -f docker-compose.yml build
            # Ensure self-signed certs exist (first deploy)
            if [ ! -f nginx/certs-selfsigned/selfsigned.crt ]; then
              sudo bash generate-selfsigned.sh
            fi
            sudo docker compose -f docker-compose.yml up -d --remove-orphans
